import os
from langchain_community.tools import tool
from dotenv import load_dotenv
from langchain_community.chat_models import ChatOpenAI
import requests
from langchain.schema import HumanMessage, SystemMessage
import base64
import json

@tool
def get_surroundings_description(input_dict: str):
    """
    Obtains a detailed visual description of the visually impaired user's surroundings using Google Street View imagery 
    and an LLM to interpret the scene.

    Args:
        input_dict (str): A dictionary containing the following keys:
            - 'location' (str): The geographic location to capture the Street View image, 
                                specified as a string in the format "latitude,longitude".
            - 'heading' (int): The compass heading in degrees for the Street View camera (0-360), 
                               where 0 is north, 90 is east, 180 is south, and 270 is west.
            - 'pitch' (int): The pitch angle in degrees for the Street View camera, where positive values 
                             tilt the camera upward and negative values tilt it downward.
            - 'size' (str, optional): The size of the requested image in pixels, formatted as "widthxheight". 
                                      Defaults to "600x400".
    
    Returns:
        str: A detailed description of the surroundings generated by the LLM.
    """
    input_dict = json.loads(input_dict)
    location = input_dict["query"].get("location")
    heading = input_dict["query"].get("heading")
    pitch = input_dict["query"].get("pitch")
    size = input_dict["query"].get("size", "600x400")  # Default size if not provided

    with open("../resources/prompt.txt", "r") as f:
        nav_prompt = f.read()

    load_dotenv()
    GMAP_API_KEY = os.getenv("GMAP_API_KEY")
    OPENAI_API_KEY = os.getenv("OPENAI_API_KEY")

    llm = ChatOpenAI(api_key=OPENAI_API_KEY, model="gpt-4o")

    base_url = "https://maps.googleapis.com/maps/api/streetview"

    params = {
        "location": location,
        "heading": heading,
        "pitch": pitch,
        "size": size,
        "key": GMAP_API_KEY
    }
    response = requests.get(base_url, params=params)

    base64_bytes = base64.b64encode(response.content)
    base64_string = base64_bytes.decode('utf-8')
    data_url_prefix = "data:image/png;base64,"
    base64_data_url = data_url_prefix + base64_string

    system_message = SystemMessage(nav_prompt)
    human_message = HumanMessage(content=[
        {"type": "text", "text": "Describe the surroundings to a visually impaired user. Be as detailed as possible."},
        {"type": "image_url", "image_url": {"url": base64_data_url}}
    ])

    prompts = [system_message, human_message]
    response = llm.invoke(prompts)
    return response


@tool
def places_nearby(input_dict: str):
    """
    Fetches a list of nearby places based on a text query using the Google Maps Places API (Text Search).

    This function sends a request to the Google Maps Places Text Search API with the given query, location, 
    and radius to retrieve a list of places relevant to the query. The results are limited by the `limit` 
    parameter and include details such as the name, address, and geographic coordinates (latitude and longitude) 
    for each place.

    Parameters:
    -----------
    input_dict (str): A dictionary containing the following keys:
        query : str
            The search query text. This can include keywords such as 'restaurants', 'hotels', 'cafes', etc., 
            optionally combined with a location (e.g., 'restaurants in New York').
        
        radius : int
            The radius (in meters) around the specified location to search for places. For example, if `radius=5000`, 
            the API will search for places within a 5-kilometer range around the given location.
        
        location : str
            The geographic location around which to search, specified in 'latitude,longitude' format 
            (e.g., '40.712776,-74.005974' for New York City). This acts as the center point of the search area.
        
        limit : int
            The maximum number of places to return. This ensures that only the top `limit` results are included 
            in the output, even if more results are available.

    Returns:
    --------
    str
        A string containing the formatted details of up to `limit` places found by the API. Each entry 
        in the output includes the place name, formatted address, and the geographic coordinates 
        (latitude, longitude) of the place, separated by newlines.

        Example output:
        "Place: Joe's Pizza, Address: 7 Carmine St, New York, NY 10014, Location: (40.730610, -73.935242)
         Place: John's Bakery, Address: 123 Main St, New York, NY 10001, Location: (40.741895, -73.989308)"

    Notes:
    ------
    - The results returned by the API are ranked by relevance to the query, though they are constrained 
      by the provided location and radius.
    - The `location` parameter must be provided as a string in 'latitude,longitude' format, 
      not as separate latitude and longitude values.
    - The maximum radius allowed by the API is 50,000 meters (50 km).
    """
    input_dict = json.loads(input_dict)
    query = input_dict.get("query")
    radius = input_dict.get("radius")
    location = input_dict.get("location")
    limit = input_dict.get("limit", 5)  # Default limit if not provided

    if not query or not radius or not location:
        return "Missing required parameters: 'query', 'radius', or 'location'."

    load_dotenv()
    GMAP_API_KEY = os.getenv("GMAP_API_KEY")
    endpoint_url = "https://maps.googleapis.com/maps/api/place/textsearch/json"

    params = {
        'query': query,
        "location": location,
        "radius": radius,
        'key': GMAP_API_KEY
    }

    response = requests.get(endpoint_url, params=params)
    places_data = response.json()

    output = []
    for index, place in enumerate(places_data["results"]):
        if index >= limit:
            break
        name = place.get("name")
        address = place.get("formatted_address")
        lat = place['geometry']['location']["lat"]
        lng = place['geometry']['location']["lng"]
        output.append(f"Place: {name}, Address: {address}, Location: ({lat}, {lng})")
    
    return "\n".join(output)


